import Category from 'src/app/models/services/Category';
import Service from 'src/app/models/services/Service';

export const categories: Category[] = [
  { id: 1, name: 'Valymas', imageUrl: 'https://t3.ftcdn.net/jpg/02/30/46/42/240_F_230464218_WsWoWtbFitehDJpi3OkK1ZMOTqdbGp3c.jpg'},
  { id: 2, name: 'Elektros darbai', imageUrl: 'https://t4.ftcdn.net/jpg/01/70/17/97/240_F_170179753_piUSFjn4xlwAKaIU14gs6FnCVij2wckc.jpg'},
  { id: 3, name: 'Santechnikos darbai', imageUrl: 'https://t4.ftcdn.net/jpg/02/16/28/29/240_F_216282910_yjxZDV8zDD2FaaBzxaQcNBhFMnmpuoFj.jpg'},
  { id: 4, name: 'Statybos darbai', imageUrl: 'https://t3.ftcdn.net/jpg/02/90/51/26/240_F_290512663_zep6YJ0mCgnlJY2tE8ooPVNP6xhEu0Gk.jpg'},
  { id: 5, name: 'Buitinės technikos pajungimas', imageUrl: 'https://t4.ftcdn.net/jpg/03/12/23/07/240_F_312230725_HDCTBEXE7g1c6sBFWdcnQJOzdhSQQkTX.jpg'},
  { id: 6, name: 'Vidaus apdailos darbai', imageUrl: 'https://t4.ftcdn.net/jpg/03/28/75/29/240_F_328752924_b2GuZzirAqIlpqLUuuUKLBjKcT87IDFj.jpg'},
  { id: 7, name: 'Baldų surinkimas', imageUrl: 'https://t4.ftcdn.net/jpg/02/33/49/67/240_F_233496733_vNlSvxuuLriXSM3L78HW7fNP3pJkl4sW.jpg'},
  { id: 8, name: 'Pervežimas', imageUrl: 'https://t4.ftcdn.net/jpg/04/28/47/97/240_F_428479723_yecIfKly5jdoEMFQvfEekQeQ2EaKjuMX.jpg'},
  { id: 9, name: 'Aplinkos tvarkymas ir priežiūra', imageUrl: 'https://t3.ftcdn.net/jpg/03/67/35/14/240_F_367351493_qvbw37oVKGJwi8jZgFWDAeyC7uRLuZfa.jpg'},
  { id: 10, name: 'Kondicionavimo sistemų bei vėdinimo sistemų darbai', imageUrl: 'https://t3.ftcdn.net/jpg/02/41/53/46/240_F_241534624_XwkSunMF8A9l2rQnWvxhCDwI4BvH3D5Q.jpg'},
  { id: 11, name: 'Apsaugos darbai', imageUrl: 'https://t4.ftcdn.net/jpg/02/19/09/69/240_F_219096975_C4t7pSztzGuCCQxiyZpwKIK8L7Moewlg.jpg'},
  { id: 12, name: 'Dujų ūkio darbai', imageUrl: 'https://t3.ftcdn.net/jpg/04/81/82/12/240_F_481821291_I1e0FeSDsETwJkHPB599a71lnZmzsMya.jpg'},
];

export const services: Service[] = [
  { id: 1, name: "Namų valymas", categoryId: 1 },
  { id: 2, name: "Ofiso valymas", categoryId: 1 },
  { id: 3, name: "Valymas po remonto darbų", categoryId: 1 },
  { id: 4, name: "Langų valymas", categoryId: 1 },
  { id: 5, name: "Minkštų baldų valymas", categoryId: 1 },
  { id: 6, name: "Kilimų valymas", categoryId: 1 },
  { id: 7, name: "Elektros instaliacijos darbai", categoryId: 2 },
  { id: 8, name: "Elektros remonto darbai", categoryId: 2 },
  { id: 9, name: "Santechnikos montavimas", categoryId: 3 },
  { id: 10, name: "Santecnikos remontas", categoryId: 3 },
  { id: 11, name: "Apdailos darbai", categoryId: 4 },
  { id: 12, name: "Griovimo darbai", categoryId: 4 },
  { id: 13, name: "Sienų tinkavimas", categoryId: 4 },
  { id: 14, name: "Kaminų valymas", categoryId: 4 },
  { id: 15, name: "Buitinės technikos įrengimas", categoryId: 5 },
  { id: 16, name: "Buitinės technikos remontas", categoryId: 5 },
  { id: 17, name: "Durų montavimas", categoryId: 6 },
  { id: 18, name: "Langų montavimas", categoryId: 6 },
  { id: 19, name: "Plytelių klojimas", categoryId: 6 },
  { id: 20, name: "Tapetavimas", categoryId: 6 },
  { id: 21, name: "Sienų ir lubų apdaila", categoryId: 6 },
  { id: 22, name: "Sienų dažymas", categoryId: 6 },
  { id: 23, name: "Staliaus darbai", categoryId: 6 },
  { id: 24, name: "Plastikinių langų reguliavimas", categoryId: 6 },
  { id: 25, name: "Įtempiamų lubų montavimas", categoryId: 6 },
  { id: 26, name: "Gipso kartono plokščių montavimas", categoryId: 6 },
  { id: 27, name: "Apšiltinimas", categoryId: 6 },
  { id: 28, name: "Garso izoliavimas", categoryId: 6 },
  { id: 29, name: "Karnizų montavimas", categoryId: 6 },
  { id: 30, name: 'Užuolaidų keitimas', categoryId: 6 },
  { id: 31, name: 'Baldų surinkimas', categoryId: 7 },
  { id: 32, name: 'Virtuvės baldų surinkimas', categoryId: 7 },
  { id: 33, name: 'Baldų pervežimas', categoryId: 8 },
  { id: 34, name: 'Statybinių medžiagų išvežimas', categoryId: 8 },
  { id: 35, name: 'Sunkių daiktų pervežimas', categoryId: 8 },
  { id: 36, name: 'Daiktų supakavimas ir išpakavimas', categoryId: 8 },
  { id: 37, name: 'Žolės pjovimas', categoryId: 9 },
  { id: 38, name: 'Sniego valymas', categoryId: 9 },
  { id: 39, name: 'Aplinkos tvarkymas', categoryId: 9 },
  { id: 40, name: 'Grindinio klojimas', categoryId: 9 },
  { id: 41, name: 'Grindinio plovimas', categoryId: 9 },
  { id: 42, name: 'Kapų tvarkymas', categoryId: 9 },
  { id: 43, name: 'Kondicionierių priežiūra', categoryId: 10 },
  { id: 44, name: 'Kondicionierių pildymas', categoryId: 10 },
  { id: 45, name: 'Kondicionierių remontas', categoryId: 10 },
  { id: 46, name: 'Kondicionierių meistro konsultacija', categoryId: 10 },
  { id: 47, name: 'Vėdinimo sistemų remontas', categoryId: 10 },
  { id: 48, name: 'Vėdinimo sistemų programavimas', categoryId: 10 },
  { id: 49, name: 'Vėdinimo sistemos apžiūra', categoryId: 10 },
  { id: 50, name: 'Vėdinimo sistemos meistro konsultacija', categoryId: 10 },
  { id: 51, name: 'Vartų automatikos montavimas', categoryId: 11 },
  { id: 52, name: 'Vartų automatikos remontas', categoryId: 11 },
  { id: 53, name: 'Apsaugos sistemų įrengimas', categoryId: 11 },
  { id: 54, name: 'Apsaugos sistemų remontas', categoryId: 11 },
  { id: 55, name: 'Vaizdo stebėjimo sistemų pajungimas', categoryId: 11 },
  { id: 56, name: 'Vaizdo stebėjimo sistemų remontas', categoryId: 11 },
  { id: 57, name: 'Priešgaistrinių daviklių instaliacija', categoryId: 11 },
  { id: 58, name: 'Priešgaistrinių daviklių remontas', categoryId: 11 },
  { id: 59, name: 'Dujų baliono keitimas', categoryId: 12 },
  { id: 60, name: 'Dujų įvedimas', categoryId: 12 }
]